from . import action_data
from . import remove_action
from . import access_management
from . import ir_ui_menu
from . import res_users
from . import ir_actions_actions
from . import hide_field
from . import models
from . import ir_ui_view
