{
    "name": "Field Service Report",
    "summary": "Make field service reports",
    "version": "17.0.2.6.0",
    "license": "AGPL-3",
    "category": "Field Service",
    "author": "Saran K",
    "depends": ["base_territory", "base_geolocalize", "resource", "contacts", "crm", "sale_management", "mail", "fieldservice", "fieldservice_crm", "fsm_order_products"],
    "data": [
        "security/ir.model.access.csv",
        'views/fsm_order_views_extension.xml',
        'data/sequence_data.xml',
        'report/paper_format.xml',
        'report/report_action.xml',
        'report/report_header.xml',
        'report/report_template.xml',
        'data/field_service_report_email_template.xml',  
        'views/field_service_report_views.xml',
        'views/field_service_report_actions.xml',
        'views/field_service_report_menu.xml',
        'views/fsm_stage.xml',
        'views/followup_recommendation.xml',
        'views/method_application.xml',
    ],
    "application": True,
    "assets": {},
}